-- ============================================================
-- ZERSU AI POSTS SCHEMA
-- Automatic AI post generation system
-- ============================================================

-- ============================================
-- 1. AI POSTS TABLE
-- Stores posts generated by Zersu AI
-- ============================================
CREATE TABLE IF NOT EXISTS public.ai_posts (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  cover_image TEXT,
  is_published BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

ALTER TABLE public.ai_posts ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ai_posts' AND policyname = 'Anyone can view published ai_posts') THEN
        CREATE POLICY "Anyone can view published ai_posts" ON public.ai_posts FOR SELECT USING (is_published = true);
    END IF;
END $$;

-- ============================================
-- 2. AI DOCUMENTATION TABLE
-- Admin writes instructions/news, AI reads
-- ============================================
CREATE TABLE IF NOT EXISTS public.ai_documentation (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('instructions', 'news')),
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

ALTER TABLE public.ai_documentation ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    -- Anyone can read (for JSON export)
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ai_documentation' AND policyname = 'Anyone can read documentation') THEN
        CREATE POLICY "Anyone can read documentation" ON public.ai_documentation FOR SELECT USING (true);
    END IF;
    
    -- Admins can manage
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ai_documentation' AND policyname = 'Admins can manage documentation') THEN
        CREATE POLICY "Admins can manage documentation" ON public.ai_documentation 
          FOR ALL USING (public.has_role(auth.uid(), 'admin'));
    END IF;
END $$;

-- ============================================
-- 3. AI POST CONFIG TABLE
-- Rate limiting and scheduling config
-- ============================================
CREATE TABLE IF NOT EXISTS public.ai_post_config (
  id TEXT PRIMARY KEY DEFAULT 'global',
  posts_today INTEGER DEFAULT 0,
  max_posts_per_day INTEGER DEFAULT 2,
  last_post_date DATE,
  last_post_at TIMESTAMP WITH TIME ZONE,
  next_scheduled_at TIMESTAMP WITH TIME ZONE,
  is_enabled BOOLEAN DEFAULT true,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

ALTER TABLE public.ai_post_config ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ai_post_config' AND policyname = 'Anyone can read ai_post_config') THEN
        CREATE POLICY "Anyone can read ai_post_config" ON public.ai_post_config FOR SELECT USING (true);
    END IF;
END $$;

-- Initialize config if not exists
INSERT INTO public.ai_post_config (id, posts_today, max_posts_per_day, is_enabled) 
VALUES ('global', 0, 2, true) 
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- 4. HELPER FUNCTIONS
-- ============================================

-- Function to check if AI can post (rate limiting)
CREATE OR REPLACE FUNCTION public.can_ai_post()
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    config_record RECORD;
    current_date DATE := CURRENT_DATE;
BEGIN
    SELECT * INTO config_record FROM public.ai_post_config WHERE id = 'global';
    
    IF config_record IS NULL THEN
        RETURN true;
    END IF;
    
    -- If not enabled, return false
    IF NOT config_record.is_enabled THEN
        RETURN false;
    END IF;
    
    -- If different day, reset counter
    IF config_record.last_post_date IS NULL OR config_record.last_post_date < current_date THEN
        UPDATE public.ai_post_config 
        SET posts_today = 0, last_post_date = current_date, updated_at = now()
        WHERE id = 'global';
        RETURN true;
    END IF;
    
    -- Check if under limit
    RETURN config_record.posts_today < config_record.max_posts_per_day;
END;
$$;

-- Function to record AI post creation
CREATE OR REPLACE FUNCTION public.record_ai_post()
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    UPDATE public.ai_post_config 
    SET 
        posts_today = posts_today + 1,
        last_post_at = now(),
        last_post_date = CURRENT_DATE,
        -- Schedule next post randomly between 8-12 hours
        next_scheduled_at = now() + (interval '8 hours' + (random() * interval '4 hours')),
        updated_at = now()
    WHERE id = 'global';
END;
$$;

-- Function to get documentation as JSON (for AI to read)
CREATE OR REPLACE FUNCTION public.get_ai_documentation_json()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    result JSONB;
BEGIN
    SELECT jsonb_build_object(
        'instructions', COALESCE(
            (SELECT content FROM public.ai_documentation WHERE type = 'instructions' ORDER BY updated_at DESC LIMIT 1),
            'You are Zersu, the AI companion of ZetsuServ blog. Create engaging posts about gaming, technology, and community updates.'
        ),
        'news', COALESCE(
            (SELECT jsonb_agg(jsonb_build_object('content', content, 'date', created_at)) 
             FROM (SELECT content, created_at FROM public.ai_documentation WHERE type = 'news' ORDER BY created_at DESC LIMIT 10) sub),
            '[]'::jsonb
        ),
        'site_stats', jsonb_build_object(
            'total_posts', (SELECT COUNT(*) FROM public.posts WHERE published = true),
            'total_users', (SELECT COUNT(*) FROM public.profiles),
            'total_challenges', (SELECT COUNT(*) FROM public.player_challenges WHERE status = 'completed')
        )
    ) INTO result;
    
    RETURN result;
END;
$$;

-- ============================================
-- 5. TRIGGER FOR AI POST GENERATION (pg_cron)
-- Note: pg_cron extension must be enabled in Supabase
-- ============================================

-- This function will be called by pg_cron
CREATE OR REPLACE FUNCTION public.trigger_ai_post_generation()
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    config_record RECORD;
BEGIN
    SELECT * INTO config_record FROM public.ai_post_config WHERE id = 'global';
    
    -- Check if we can post
    IF NOT public.can_ai_post() THEN
        RAISE NOTICE 'AI post limit reached for today';
        RETURN;
    END IF;
    
    -- Check if scheduled time has passed (random interval check)
    IF config_record.next_scheduled_at IS NOT NULL AND config_record.next_scheduled_at > now() THEN
        RAISE NOTICE 'Not yet time for next AI post. Scheduled at: %', config_record.next_scheduled_at;
        RETURN;
    END IF;
    
    -- The actual post generation will be done via Edge Function
    -- This function just signals that it's time to generate
    -- We'll use Supabase realtime or a webhook to trigger the Edge Function
    
    RAISE NOTICE 'AI post generation triggered at %', now();
END;
$$;

-- ============================================
-- 6. ENABLE pg_cron (Run this manually in Supabase SQL Editor)
-- ============================================
-- Note: Uncomment and run these commands manually in Supabase Dashboard
-- 
-- CREATE EXTENSION IF NOT EXISTS pg_cron;
-- 
-- -- Schedule to run every hour and check if we should generate a post
-- SELECT cron.schedule(
--     'ai-post-check',
--     '0 * * * *',  -- Every hour at minute 0
--     $$SELECT public.trigger_ai_post_generation()$$
-- );

-- ============================================
-- INSTRUCTIONS FOR MANUAL SETUP
-- ============================================
DO $$
BEGIN
    RAISE NOTICE '============================================';
    RAISE NOTICE 'MANUAL SETUP REQUIRED FOR pg_cron:';
    RAISE NOTICE '1. Go to Supabase Dashboard -> Database -> Extensions';
    RAISE NOTICE '2. Enable the pg_cron extension';
    RAISE NOTICE '3. Run the commented pg_cron schedule commands above';
    RAISE NOTICE '============================================';
END $$;
